// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/projects"
type AppRouteHandlerRoutes = "/api/agent/generate" | "/api/config" | "/api/debug/agnes-video/[remoteTaskId]" | "/api/files/[...path]" | "/api/images/generate" | "/api/projects" | "/api/projects/[id]" | "/api/tasks" | "/api/tasks/[id]" | "/api/tasks/[id]/resume" | "/api/tasks/sync" | "/api/text/generate" | "/api/uploads" | "/api/videos/generate"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent/generate": {}
  "/api/config": {}
  "/api/debug/agnes-video/[remoteTaskId]": { "remoteTaskId": string; }
  "/api/files/[...path]": { "path": string[]; }
  "/api/images/generate": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/tasks": {}
  "/api/tasks/[id]": { "id": string; }
  "/api/tasks/[id]/resume": { "id": string; }
  "/api/tasks/sync": {}
  "/api/text/generate": {}
  "/api/uploads": {}
  "/api/videos/generate": {}
  "/projects": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
